version: '3.8'
services:
  identix-wallets-api:
    container_name: 'identix-wallets'
    image: 'identix-wallets'
    hostname: identix-wallets
    networks:
      - app-local-net
    volumes:
      - ../../.env:/usr/src/app/.env
    environment:
      - HTTP_PORT=${BACKEND_HTTP_API_PORT}
    ports:
      - "9000:3000"
    command: [ "yarn", "start" ]


networks:
  app-local-net:
    external: false
    driver: bridge
    name: app-local-net
